"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type License = { id:number; productName:string; vendor:string; category:string; startDate:string; expirationDate:string; cost:number; currency:string; description:string; createdAt:string; updatedAt:string };
const today = new Date();
const isoFromNow = (days:number) => { const d=new Date(today); d.setDate(d.getDate()+days); return d.toISOString().slice(0,10) };
const seed:License[] = [
 {id:1,productName:"Microsoft 365 Business",vendor:"Microsoft",category:"Üretkenlik",startDate:"2025-09-01",expirationDate:isoFromNow(12),cost:14800,currency:"USD",description:"120 kullanıcı · yıllık kurumsal plan",createdAt:"2025-09-01",updatedAt:"2026-08-12"},
 {id:2,productName:"Figma Organization",vendor:"Figma",category:"Tasarım",startDate:"2025-10-15",expirationDate:isoFromNow(24),cost:5400,currency:"USD",description:"25 editör lisansı",createdAt:"2025-10-15",updatedAt:"2026-07-18"},
 {id:3,productName:"Slack Business+",vendor:"Salesforce",category:"İletişim",startDate:"2026-01-10",expirationDate:isoFromNow(68),cost:9600,currency:"USD",description:"Yıllık ekip aboneliği",createdAt:"2026-01-10",updatedAt:"2026-06-02"},
 {id:4,productName:"Adobe Creative Cloud",vendor:"Adobe",category:"Tasarım",startDate:"2025-08-02",expirationDate:isoFromNow(-8),cost:7200,currency:"USD",description:"12 kullanıcı",createdAt:"2025-08-02",updatedAt:"2026-05-29"},
 {id:5,productName:"GitHub Enterprise",vendor:"GitHub",category:"Geliştirme",startDate:"2026-03-01",expirationDate:isoFromNow(142),cost:11200,currency:"USD",description:"50 kullanıcı",createdAt:"2026-03-01",updatedAt:"2026-08-05"},
 {id:6,productName:"Notion Enterprise",vendor:"Notion",category:"Üretkenlik",startDate:"2025-11-20",expirationDate:isoFromNow(4),cost:6900,currency:"USD",description:"85 kullanıcı · yenileme görüşülüyor",createdAt:"2025-11-20",updatedAt:"2026-08-15"},
];
const emptyForm={productName:"",vendor:"",category:"",startDate:"",expirationDate:"",cost:"",currency:"USD",description:""};
function remainingDays(date:string){return Math.ceil((new Date(`${date}T23:59:59`).getTime()-Date.now())/86400000)}
function statusOf(date:string,threshold=30){const d=remainingDays(date);return d<=0?"Süresi Doldu":d<=threshold?"Yaklaşıyor":"Aktif"}
function money(v:number,c:string){return new Intl.NumberFormat("tr-TR",{style:"currency",currency:c,maximumFractionDigits:0}).format(v)}
function shortDate(d:string){return new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${d}T12:00:00`))}

export default function Home(){
 const [licenses,setLicenses]=useState(seed),[modalOpen,setModalOpen]=useState(false),[editing,setEditing]=useState<number|null>(null);
 const [form,setForm]=useState(emptyForm),[query,setQuery]=useState(""),[category,setCategory]=useState("Tümü"),[status,setStatus]=useState("Tümü");
 useEffect(()=>{fetch("/api/licenses").then(r=>r.ok?r.json():Promise.reject()).then(({licenses:rows})=>{if(rows.length)setLicenses(rows)}).catch(()=>{})},[]);
 const counts=useMemo(()=>({active:licenses.filter(l=>statusOf(l.expirationDate)==="Aktif").length,soon:licenses.filter(l=>statusOf(l.expirationDate)==="Yaklaşıyor").length,expired:licenses.filter(l=>statusOf(l.expirationDate)==="Süresi Doldu").length}),[licenses]);
 const usdTotal=licenses.reduce((s,l)=>s+(l.currency==="USD"?l.cost:0),0),categories=["Tümü",...Array.from(new Set(licenses.map(l=>l.category)))];
 const filtered=licenses.filter(l=>{const q=query.toLocaleLowerCase("tr");return(!q||`${l.productName} ${l.vendor}`.toLocaleLowerCase("tr").includes(q))&&(category==="Tümü"||l.category===category)&&(status==="Tümü"||statusOf(l.expirationDate)===status)});
 const renewals=[...licenses].filter(l=>remainingDays(l.expirationDate)<=30).sort((a,b)=>remainingDays(a.expirationDate)-remainingDays(b.expirationDate));
 const openAdd=()=>{setEditing(null);setForm(emptyForm);setModalOpen(true)},openEdit=(l:License)=>{setEditing(l.id);setForm({...l,cost:String(l.cost)});setModalOpen(true)};
 const submit=async(e:FormEvent)=>{e.preventDefault();const payload={...form,cost:Number(form.cost),...(editing?{id:editing}:{})};try{const r=await fetch("/api/licenses",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error();const {license}=await r.json();setLicenses(items=>editing?items.map(l=>l.id===editing?license:l):[license,...items])}catch{const now=new Date().toISOString();if(editing)setLicenses(items=>items.map(l=>l.id===editing?{...l,...form,cost:Number(form.cost),updatedAt:now}:l));else setLicenses(items=>[{...form,id:Date.now(),cost:Number(form.cost),createdAt:now,updatedAt:now},...items])}setModalOpen(false)};
 const remove=async(id:number)=>{if(confirm("Bu lisans kaydını silmek istediğinize emin misiniz?")){setLicenses(items=>items.filter(l=>l.id!==id));try{await fetch(`/api/licenses?id=${id}`,{method:"DELETE"})}catch{}}};
 return <div className="app-shell">
  <main><header><div className="top-brand"><span className="brand-mark">L</span><span><b>LicenceFlow</b><small>Lisans yönetim paneli</small></span></div><div className="header-actions"><button className="icon-button">⌕</button><button className="icon-button notify">♢<span/></button><button className="primary" onClick={openAdd}><b>＋</b> Lisans Ekle</button></div></header>
  <section className="welcome"><div><div className="eyebrow">GENEL BAKIŞ</div><h2>Günaydın, Mehmet <span>👋</span></h2><p>Lisans portföyünüzün güncel durumu. <b>{counts.soon} yenileme</b> yaklaşıyor.</p></div><div className="date-pill">◷ &nbsp;{new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"long",year:"numeric"}).format(today)}</div></section>
  <section className="cards"><Metric icon="▣" tone="blue" label="TOPLAM LİSANS" value={licenses.length} note={<><b className="up">↗ 2</b> geçen aya göre</>}/><Metric icon="✓" tone="green" label="AKTİF LİSANS" value={counts.active} note={<>Tüm lisansların %{Math.round(counts.active/licenses.length*100||0)}’i</>}/><Metric icon="◷" tone="orange" label="YAKLAŞAN YENİLEMELER" value={counts.soon} note={<b className="warn">30 gün içinde</b>}/><Metric icon="!" tone="red" label="SÜRESİ DOLANLAR" value={counts.expired} note={<b className="danger">İşlem gerekli</b>}/><Metric icon="$" tone="purple" extra="cost-card" label="YILLIK TOPLAM MALİYET" value={money(usdTotal,"USD")} note={<><b className="up">↘ %4,8</b> optimizasyon</>}/></section>
  <section className="dashboard-grid"><div className="panel renewals"><div className="panel-head"><div><h2>Yaklaşan Yenilemeler</h2><p>Önümüzdeki 30 gün ve süresi dolanlar</p></div><button onClick={()=>document.getElementById("licenses")?.scrollIntoView({behavior:"smooth"})}>Tümünü gör →</button></div><LicenseTable rows={renewals.slice(0,5)} onEdit={openEdit} onRemove={remove}/></div><div className="panel chart"><div className="panel-head"><div><h2>Durum Dağılımı</h2><p>Mevcut lisans portföyü</p></div><button>⋯</button></div><div className="donut" style={{background:`conic-gradient(#16a36a 0 ${counts.active/licenses.length*100}%,#f0a436 0 ${(counts.active+counts.soon)/licenses.length*100}%,#e95858 0)`}}><div><b>{licenses.length}</b><span>Toplam</span></div></div><div className="legend"><p><span className="dot green-dot"/>Aktif <b>{counts.active}</b></p><p><span className="dot orange-dot"/>Yaklaşıyor <b>{counts.soon}</b></p><p><span className="dot red-dot"/>Süresi Doldu <b>{counts.expired}</b></p></div></div></section>
  <section className="licenses-page" id="licenses"><div className="list-top"><div><h2>Tüm Lisanslar</h2><p>{licenses.length} lisans kaydı listeleniyor</p></div></div><div className="filters"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün veya tedarikçi ara..."/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>Tümü</option><option>Aktif</option><option>Yaklaşıyor</option><option>Süresi Doldu</option></select></div><div className="panel full-table"><LicenseTable rows={filtered} onEdit={openEdit} onRemove={remove}/></div></section></main>
  {modalOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModalOpen(false)}><div className="modal"><div className="modal-head"><div><span className="modal-icon">＋</span><div><h2>{editing?"Lisansı Düzenle":"Yeni Lisans Ekle"}</h2><p>Lisans bilgilerini eksiksiz girin.</p></div></div><button onClick={()=>setModalOpen(false)}>×</button></div><form onSubmit={submit}><div className="form-grid"><label className="wide">Ürün / hizmet adı *<input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})} placeholder="Örn. Microsoft 365 Business"/></label><label>Tedarikçi *<input required value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})} placeholder="Firma adı"/></label><label>Kategori *<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Kategori seçin</option>{["Üretkenlik","Tasarım","İletişim","Geliştirme","Güvenlik","Diğer"].map(x=><option key={x}>{x}</option>)}</select></label><label>Başlangıç tarihi *<input type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Bitiş / yenileme tarihi *<input type="date" required value={form.expirationDate} onChange={e=>setForm({...form,expirationDate:e.target.value})}/></label><label>Maliyet *<input type="number" min="0" required value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})} placeholder="0"/></label><label>Para birimi<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>USD</option><option>EUR</option><option>TRY</option><option>GBP</option></select></label><label className="wide">Açıklama / not<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Lisansla ilgili notlar..."/></label></div><div className="info-box"><b>ⓘ Otomatik hesaplama</b><span>Kalan gün ve lisans durumu, bitiş tarihine göre otomatik hesaplanır.</span></div><div className="form-actions"><button type="button" onClick={()=>setModalOpen(false)}>Vazgeç</button><button className="primary" type="submit">{editing?"Değişiklikleri Kaydet":"Lisansı Kaydet"}</button></div></form></div></div>}</div>
}
function Metric({icon,tone,label,value,note,extra=""}:{icon:string;tone:string;label:string;value:string|number;note:React.ReactNode;extra?:string}){return <article className={extra}><span className={`card-icon ${tone}`}>{icon}</span><small>{label}</small><h3>{value}</h3><p>{note}</p></article>}
function LicenseTable({rows,onEdit,onRemove}:{rows:License[];onEdit:(l:License)=>void;onRemove:(id:number)=>void}){return <div className="table-wrap"><table><thead><tr><th>ÜRÜN / HİZMET</th><th>TEDARİKÇİ</th><th>BİTİŞ TARİHİ</th><th>KALAN GÜN</th><th>MALİYET</th><th>DURUM</th><th/></tr></thead><tbody>{rows.map(l=>{const days=remainingDays(l.expirationDate),status=statusOf(l.expirationDate);return <tr key={l.id}><td><span className={`product-logo logo-${l.id%5}`}>{l.productName[0]}</span><div><b>{l.productName}</b><small>{l.category}</small></div></td><td>{l.vendor}</td><td>{shortDate(l.expirationDate)}</td><td><b className={days<=0?"text-red":days<=30?"text-orange":""}>{days<=0?`${Math.abs(days)} gün geçti`:`${days} gün`}</b></td><td><b>{money(l.cost,l.currency)}</b><small>/ yıl</small></td><td><span className={`status status-${status.toLowerCase().replaceAll(" ","-").replace("ü","u").replace("ı","i")}`}><i/>{status}</span></td><td className="row-actions"><button aria-label="Düzenle" onClick={()=>onEdit(l)}>✎</button><button aria-label="Sil" onClick={()=>onRemove(l.id)}>⌫</button></td></tr>})}{!rows.length&&<tr><td className="no-results" colSpan={7}>Aramanızla eşleşen kayıt bulunamadı.</td></tr>}</tbody></table></div>}
